/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test_requests


import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.client.engine.cio.*
import kotlinx.coroutines.*
import kotlinx.serialization.*
import io.ktor.client.features.json.*
import io.ktor.client.features.json.serializer.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}


suspend fun test(){
    //val client = HttpClient(CIO)
    
    
}
@Serializable
data class AuthStatus(val status:Int,val token:String)

fun main() {
    val client = HttpClient(CIO){
        install(JsonFeature){
            serializer = KotlinxSerializer()
        }
    }
    GlobalScope.launch(Dispatchers.IO) {
        val response: AuthStatus = client.post("http://localhost:8080/auth") {
        
        }
        
        println(response.toString())
        
    }
    Thread.sleep(2000L)
    println()
}
