/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test_requests


import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.client.engine.cio.*
import kotlinx.coroutines.*
import kotlinx.serialization.*
import io.ktor.client.features.json.*
import io.ktor.client.features.json.serializer.*
import io.ktor.client.request.forms.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}


suspend fun test(){
    //val client = HttpClient(CIO)
    
    
}




fun main() {
    val client = HttpClient(CIO){
        install(JsonFeature){
            serializer = KotlinxSerializer()
        }
    }
    GlobalScope.launch(Dispatchers.IO) {
        val response = Auth(client,
                            User("testt","123456"))
        
        val response2 = AddTask(client,response.token)
        

        println(response2)
        
    }

    
    while(true){
       
    }
    println()
}
