/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab3;


public class App {
    

    public static void main(String[] args) {
        GUIApp app = new GUIApp();
        app.run();
        
        
    }
}
